import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
[font]
size = 12.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
padding = { x = 0, y = 0}
dynamic_padding = true
decorations = "None"
opacity = 0.85
#opacity = 1
#blur = true # (works on KDE Wayland)
decorations_theme_variant = "Dark"

[scrolling]
multiplier = 5

[selection]
#save_to_clipboard = true

[mouse]
hide_when_typing = true

